### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by Mayingj** [FuyaLuo/MornGAN#1]
Outstanding work!Thank you for your work！ May I ask when you will open source the code？

**Comment by FuyaLuo** [comment]
> Outstanding work!Thank you for your work！ May I ask when you will open source the code？

Thank you for your endorsement of this work. The manuscript is still under review and the code will be available after the manuscript is accepted.

**Comment by deepNeuralNick** [comment]
Hi @FuyaLuo, your work in the field is outstanding!, can we have an update on the code release?

**Comment by FuyaLuo** [comment]
> Hi @FuyaLuo, your work in the field is outstanding!, can we have an update on the code release?

Thank you for your endorsement of this work. The manuscript is still under review and the code will be available after the manuscript is accepted.
